=== SURFnet/sp-dashboard/app/Resources/schemas/attributes.scheme.json
{
	"definitions": {},
	"$schema": "http://json-schema.org/draft-07/schema#", 
	"title": "Root",
	"type": "array",
	"default": [],
	"items":{
		"$id": "#root/items", 
		"title": "Items", 
		"type": "object",
		"required": [
			"id",
			"form",
			"detail",
			"urns"
		],
		"properties": {
			"id": {
				"$id": "#root/items/id", 
				"title": "Id", 
				"type": "string",
				"default": "",
				"examples": [
					"givenName"
				],
				"pattern": "^[a-z][a-zA-Z]*$"
			},
			"form": {
				"$id": "#root/items/form", 
				"title": "Form", 
				"type": "object",
				"required": [
					"translations"
				],
				"properties": {
					"excludeOnEntityType": {
						"$id": "#root/items/form/excludeOnEntityType",
						"title": "Exclude on entity type",
						"type": "array",
						"default": [],
						"items":{
							"$id": "#root/items/form/excludeOnEntityType/items",
							"title": "Items",
							"type": "string",
							"default": "",
							"enum": [
								"saml20",
								"oidcng",
								"oauth20_rs",
								"oauth20_ccc"
							]
						}
					},
					"translations": {
						"$id": "#root/items/form/translations",
						"title": "Translations",
						"type": "object",
						"required": [
							"en"
						],
						"patternProperties": {
							"^en$": {
								"$id": "#root/items/form/translations/en",
								"title": "En",
								"type": "object",
								"required": [
									"label",
									"info"
								],
								"properties": {
									"label": {
										"$id": "#root/items/form/translations/en/label",
										"title": "Label",
										"type": "string",
										"default": "",
										"examples": [
											"Given name attribute"
										]
									},
									"info": {
										"$id": "#root/items/form/translations/en/info",
										"title": "Info",
										"type": "string",
										"default": ""
									}
								}
							}
						},
						"additionalProperties": false
					}
				}
			}
,
			"detail": {
				"$id": "#root/items/detail", 
				"title": "Detail", 
				"type": "object",
				"required": [
					"en"
				],
				"patternProperties": {
					"^en$": {
						"$id": "#root/items/detail/en", 
						"title": "En", 
						"type": "object",
						"required": [
							"label",
							"info"
						],
						"properties": {
							"label": {
								"$id": "#root/items/detail/en/label", 
								"title": "Label", 
								"type": "string",
								"default": "",
								"examples": [
									"Given name attribute"
								]
							},
							"info": {
								"$id": "#root/items/detail/en/info", 
								"title": "Info", 
								"type": "string",
								"default": ""
							}
						}
					}
				},
				"additionalProperties": false
			}
,
			"urns": {
				"$id": "#root/items/urns", 
				"title": "Urns", 
				"type": "array",
				"default": [],
				"items":{
					"$id": "#root/items/urns/items", 
					"title": "Items", 
					"type": "string",
					"default": "",
					"examples": [
						"urn:mace:dir:attribute-def:givenName"
					]
				}
			}
		}
	}
}

=== SURFnet/sp-dashboard/tests/unit/Infrastructure/DashboardBundle/Repository/Fixtures/attributes.json
[
  {
    "id": "givenName",
    "form" : {
      "translations" : {
        "en": {
          "label": "Given name attribute",
          "info": "Text should be set in web translations"
        }
      }
    },
    "detail" : {
      "en": {
        "label": "Given name attribute",
        "info": "Text should be set in web translations"
      }
    },
    "urns": [
      "urn:mace:dir:attribute-def:givenName",
      "urn:oid:2.5.4.42"
    ]
  },
  {
    "id": "surName",
    "form" : {
      "translations" : {
        "en": {
          "label": "Sur name attribute",
          "info": "Text should be set in web translations"
        }
      }
    },
    "detail" : {
      "en": {
        "label": "Sur name attribute",
        "info": "Text should be set in web translations"
      }
    },
    "urns": [
      "urn:mace:dir:attribute-def:sn",
      "urn:oid:2.5.4.4"
    ]
  },
  {
    "id": "commonName",
    "form" : {
      "translations" : {
        "en": {
          "label": "Common name attribute",
          "info": "Text should be set in web translations"
        }
      }
    },
    "detail" : {
      "en": {
        "label": "Common name attribute",
        "info": "Text should be set in web translations"
      }
    },
    "urns": [
      "urn:mace:dir:attribute-def:cn",
      "urn:oid:2.5.4.3"
    ]
  },
  {
    "id": "displayName",
    "form" : {
      "translations" : {
        "en": {
          "label": "Display name attribute",
          "info": "Text should be set in web translations"
        }
      }
    },
    "detail" : {
      "en": {
        "label": "Display name attribute",
        "info": "Text should be set in web translations"
      }
    },
    "urns": [
      "urn:mace:dir:attribute-def:displayName",
      "urn:oid:2.16.840.1.113730.3.1.241"
    ]
  },
  {
    "id": "emailAddress",
    "form" : {
      "translations" : {
        "en": {
          "label": "Email address attribute",
          "info": "Text should be set in web translations"
        }
      }
    },
    "detail" : {
      "en": {
        "label": "Email address attribute",
        "info": "Text should be set in web translations"
      }
    },
    "urns": [
      "urn:mace:dir:attribute-def:mail",
      "urn:oid:0.9.2342.19200300.100.1.3"
    ]
  },
  {
    "id": "organization",
    "form" : {
      "translations" : {
        "en": {
          "label": "Organization attribute",
          "info": "Text should be set in web translations"
        }
      }
    },
    "detail" : {
      "en": {
        "label": "Organization attribute",
        "info": "Text should be set in web translations"
      }
    },
    "urns": [
      "urn:mace:terena.org:attribute-def:schacHomeOrganization",
      "urn:oid:1.3.6.1.4.1.25178.1.2.9"
    ]
  },
  {
    "id": "organizationType",
    "form" : {
      "translations" : {
        "en": {
          "label": "Organization  type attribute",
          "info": "Text should be set in web translations"
        }
      }
    },
    "detail" : {
      "en": {
        "label": "Organization  type attribute",
        "info": "Text should be set in web translations"
      }
    },
    "urns": [
      "urn:mace:terena.org:attribute-def:schacHomeOrganizationType",
      "urn:oid:1.3.6.1.4.1.25178.1.2.10"
    ]
  },
  {
    "id": "organizationUnit",
    "form" : {
      "translations" : {
        "en": {
          "label": "Organization unit attribute",
          "info": "Text should be set in web translations"
        }
      }
    },
    "detail" : {
      "en": {
        "label": "Organization unit attribute",
        "info": "Text should be set in web translations"
      }
    },
    "urns": [
      "urn:mace:dir:attribute-def:ou",
      "urn:oid:1.3.6.1.4.1.25178.1.2.10"
    ]
  },
  {
    "id": "affiliation",
    "form" : {
      "translations" : {
        "en": {
          "label": "Affiliation attribute",
          "info": "Text should be set in web translations"
        }
      }
    },
    "detail" : {
      "en": {
        "label": "Affiliation attribute",
        "info": "Text should be set in web translations"
      }
    },
    "urns": [
      "urn:mace:dir:attribute-def:eduPersonAffiliation",
      "urn:oid:1.3.6.1.4.1.5923.1.1.1.1"
    ]
  },
  {
    "id": "entitlement",
    "form" : {
      "translations" : {
        "en": {
          "label": "Entitlement attribute",
          "info": "Text should be set in web translations"
        }
      }
    },
    "detail" : {
      "en": {
        "label": "Entitlement attribute",
        "info": "Text should be set in web translations"
      }
    },
    "urns": [
      "urn:mace:dir:attribute-def:eduPersonEntitlement",
      "urn:oid:1.3.6.1.4.1.5923.1.1.1.7"
    ]
  },
  {
    "id": "principleName",
    "form" : {
      "translations" : {
        "en": {
          "label": "Principle name attribute",
          "info": "Text should be set in web translations"
        }
      }
    },
    "detail" : {
      "en": {
        "label": "Principle name attribute",
        "info": "Text should be set in web translations"
      }
    },
    "urns": [
      "urn:mace:dir:attribute-def:eduPersonPrincipalName",
      "urn:oid:1.3.6.1.4.1.5923.1.1.1.6"
    ]
  },
  {
    "id": "uid",
    "form" : {
      "translations" : {
        "en": {
          "label": "Uid attribute",
          "info": "Text should be set in web translations"
        }
      }
    },
    "detail" : {
      "en": {
        "label": "Uid attribute",
        "info": "Text should be set in web translations"
      }
    },
    "urns": [
      "urn:mace:dir:attribute-def:uid",
      "urn:oid:0.9.2342.19200300.100.1.1"
    ]
  },
  {
    "id": "preferredLanguage",
    "form" : {
      "translations" : {
        "en": {
          "label": "Preferred language attribute",
          "info": "Text should be set in web translations"
        }
      }
    },
    "detail" : {
      "en": {
        "label": "Preferred language attribute",
        "info": "Text should be set in web translations"
      }
    },
    "urns": [
      "urn:mace:dir:attribute-def:preferredLanguage",
      "urn:oid:2.16.840.1.113730.3.1.39"
    ]
  },
  {
    "id": "personalCode",
    "form" : {
      "translations" : {
        "en": {
          "label": "Personal code attribute",
          "info": "Text should be set in web translations"
        }
      }
    },
    "detail" : {
      "en": {
        "label": "Personal code attribute",
        "info": "Text should be set in web translations"
      }
    },
    "urns": [
      "urn:schac:attribute-def:schacPersonalUniqueCode",
      "urn:oid:1.3.6.1.4.1.1466.155.121.1.15"
    ]
  },
  {
    "id": "scopedaffiliation",
    "form" : {
      "translations" : {
        "en": {
          "label": "Scoped affiliation attribute",
          "info": "Text should be set in web translations"
        }
      }
    },
    "detail" : {
      "en": {
        "label": "Scoped affiliation attribute",
        "info": "Text should be set in web translations"
      }
    },
    "urns": [
      "urn:mace:dir:attribute-def:eduPersonScopedAffiliation",
      "urn:oid:1.3.6.1.4.1.5923.1.1.1.9"
    ]
  },
  {
    "id": "eduPersonTargetedID",
    "form" : {
      "excludeOnEntityType": [
        "oidcng"
      ],
      "translations" : {
        "en": {
          "label": "Edu person targeted ID attribute",
          "info": "Text should be set in web translations"
        }
      }
    },
    "detail" : {
      "en": {
        "label": "Edu person targeted ID attribute",
        "info": "Text should be set in web translations"
      }
    },
    "urns": [
      "urn:mace:dir:attribute-def:eduPersonTargetedID",
      "urn:oid:1.3.6.1.4.1.5923.1.1.1.10"
    ]
  }
]
